version: '3'
services:
  prometheus:
    image: prom/prometheus:v2.22.0
    restart: always
    ports:
      - "9999:9090"
    links:
      - blackbox_exporter
      - alertmanager
    volumes:
      - "./config:/config"
      - "./data/prometheus-storage:/data"
      - "./prometheus_api:/etc/default/prometheus"
    command:
      - '--config.file=/config/prometheus.yml'
      - '--storage.tsdb.retention.time=720h'
      - '--storage.tsdb.path=/data'
      - '--web.enable-admin-api'
    user: root
    networks:
      naxa-prometheus-nw:

#  file_size_exporter:
#    image: nischalstha/prometheus-dir-size-exporter:v1
#    user: root
#    ports: 
#      - 9944:8000
#    volumes:
#      - ./config:/code/config
#      - /srv/Projects:/srv/Projects
#      - /root/srv:/root/srv
#      - /home:/home
#      - /var/log:/var/log
#      - /opt:/opt
#      - /var/lib/docker/overlay2:/var/lib/docker/overlay2
#    networks:
#      naxa-prometheus-nw:

#  filestat_exporter:
#    image: mdoubez/filestat_exporter
#    restart: always
#    ports:
#      - 9943:9943
#    command: 
#      - -config.file=/config/filestat_exporter.yml
#    volumes:
#      - ./config:/config
#      - /srv/Projects:/data/srv/Projects
#    networks:
#      naxa-prometheus-nw:
    

  blackbox_exporter:
    image: prom/blackbox-exporter:v0.18.0
    restart: always
    ports:
     - "9115:9115"
    volumes:
      - "./config:/config"
    command: --config.file=/config/blackbox.yml
    networks:
      - naxa-prometheus-nw

  domain_exporter:
    image: caarlos0/domain_exporter
    restart: always
    ports:
     - "9222:9222"
    volumes:
     - "./config:/config"
  command: --config.file=/config/domains.yml
  networks:
     - naxa-prometheus-nw

  # nginx_exporter_139:
  #   image: nginx/nginx-prometheus-exporter:0.8.0
  #   restart: always
  #   # ports:
  #   #   - "9113:9113"
  #   networks:
  #   command: -nginx.scrape-uri=http://139.59.67.104/metrics
  #   networks:
  #     - naxa-prometheus-nw

  # nginx_exporter_bhumi:
  #   image: nginx/nginx-prometheus-exporter:0.8.0
  #   restart: always
  #   # ports:
  #   #   - "9113:9113"
  #   command: -nginx.scrape-uri=http://202.45.147.55/metrics
  #   networks:
  #     - naxa-prometheus-nw

  node-exporter:
    image: prom/node-exporter:v1.0.1
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    restart: always
  #   # ports:
  #   #   - "9100:9100"
    networks:
      - naxa-prometheus-nw

#  cadvisor:
#    image: gcr.io/cadvisor/cadvisor:v0.38.6
#    container_name: cadvisor
#    volumes:
#      - /:/rootfs:ro
#      - /var/run:/var/run:rw
#      - /sys:/sys:ro
#      - /var/lib/docker:/var/lib/docker:ro
#      - /cgroup:/cgroup:ro #doesn't work on MacOS only for Linux
#    restart: always
#     ports:
#       - "8080:8080"
#    networks:
#      - naxa-prometheus-nw

  alertmanager:
    image: prom/alertmanager:v0.21.0
    restart: always
#    ports:
#      - "9093:9093"
    volumes:
      - "./data/alertmanager:/data"
      - "./config:/config"
    command: --config.file=/config/alertmanager.yml --storage.path=/data --cluster.advertise-address=0.0.0.0:9093
    user: "1000:1000"
    networks:
      - naxa-prometheus-nw

  grafana:
    image: grafana/grafana:9.5.5
    ports:
      - '9015:3000'
    restart: always
    volumes:
      - "./data/grafana/provisioning/:/etc/grafana/provisioning/"
      - "./data/grafana-storage:/var/lib/grafana"
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
      - GF_SERVER_ROOT_URL=${GRAFANA_ROOT_URL}
    networks:
      - naxa-prometheus-nw
    user: '472'

  influxdb:
    image: influxdb:1.8
    restart: always
    volumes: 
      - ./data/influxdb:/var/lib/influxdb
    environment: 
      - INFLUXDB_DB=${INFLUXDB_DB}
      - INFLUXDB_USERNAME=${INFLUXDB_USERNAME}
      - INFLUXDB_PASSWORD=${INFLUXDB_PASSWORD}
    networks:
      - naxa-prometheus-nw

networks:
  naxa-prometheus-nw:
    driver: bridge
