groups:
- name: SiteDownName
  rules:
  - alert: SiteDown
    expr: probe_success < 1
    for: 7m
    labels:
      severity: page
      type: http
    annotations:
      identifier: '{{ $labels.job }}'
      description: '{{ $labels.instance }} (http) is unreachable.'

#  - alert: Repair Assessment Site
#    expr:  probe_success{instance=~'.*assessment.*'} < 1
#    for: 7m
#    labels:
#      severity: page
#      type: repair-cic-assessment-dev
#    annotations:
#      identifier: '{{ $labels.job }}'
#      description: '{{ $labels.instance }}(http) is trying to repair iteself.'

#  - alert: Repair Landslide Site
#    expr: probe_success{instance=~'.*landslide.*'} < 1
#    for: 7m
#    labels:
#      severity: page
#      type: repair-landslide-dev
#    annotations:
#      identifier: '{{ $labels.job }}'
#      description: '{{ $labels.instance }}(http) is trying to repair iteself.'

#  - alert: Repair Hydro Site Demo
#    expr: probe_success{instance=~'.*hydro.*'} < 1
#    for: 7m
#    labels:
#      severity: page
#      type: repair-hydro
#    annotations:
#      identifier: '{{ $labels.job }}'
#      description: '{{ $labels.instance }}(http) is trying to repair iteself.'

- name: SSLExpiry
  rules:
  - alert: SSLExpiry
    expr: (probe_ssl_earliest_cert_expiry{} - time()) < 1728000
    for: 1m
    labels:
      severity: page
      type: ssl
    annotations:
      identifier: '{{ $labels.job }}'
      description: '{{ $labels.instance }} (http) SSL is expiring soon.'

#- name: HighCPU
#  rules:
#  - alert: HighCPU
#    expr: node_load5 > 10
#    for: 20s
#    labels:
#      severity: server
#      type: cpu
#    annotations:
#      identifier: '{{ $labels.job }}'
#      description: '{{ $labels.job }} has > 80% CPU usage.'

- name: LowOnSpace
  rules:
  - alert: LowOnSpace
    expr: (node_filesystem_avail_bytes{device="/dev/vda1",fstype="ext4",instance="node-exporter:9100",job="node-exporter-139",mountpoint="/"} / (1024*1024*1024)) < 2
    for: 30s
    labels:
      severity: server
      type: hdd
    annotations:
      identifier: '{{ $labels.job }}'
      description: '{{ $labels.job }} is low on HDD Space.'

- name: LowOnSpaceBhumi
  rules:
  - alert: LowOnSpaceBhumi
    expr: (node_filesystem_avail_bytes{device="/dev/mapper/ubuntu--vg-ubuntu--lv",fstype="ext4",instance="202.45.147.55:80",job="node-exporter-bhumi",mountpoint="/"} / (1024*1024*1024)) < 200
    for: 30s
    labels:
      severity: server
      type: hdd
    annotations:
      identifier: '{{ $labels.job }}'
      description: '{{ $labels.job }} is low on HDD Space.'


#############################################################################
######################   Domain Expiration Rules ############################
#############################################################################

- name: domain
  rules:
  - alert: DomainExpiringLessThen30Days
    expr: domain_expiry_days != -1 AND domain_expiry_days < 30 AND domain_expiry_days > 5
    for: 1h
    labels:
      severity: warning
    annotations:
      description: 'Domain {{ $labels.domain }} will expire in less than 30 days'
      summary: '{{ $labels.domain }}: domain is expiring'

  - alert: DomainExpiringLessThen5Days
    expr: domain_expiry_days != -1 AND domain_expiry_days <= 5
    for: 1h
    labels:
      severity: page
    annotations:
      description: 'Domain {{ $labels.domain }} will expire in less than 5 days'
      summary: '{{ $labels.domain }}: domain is expiring'

  - alert: DomainProbeFailure
    expr: domain_probe_success == 0
    for: 1h
    labels:
      severity: warning
    annotations:
      description: 'Domain {{ $labels.domain }} is not valid. Cannot probe'
      summary: '{{ $labels.domain }}: cannot probe'
